import Head from 'next/head'
import Card from '../components/card/card'
const Home = () => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-3xl font-bold underline text-indigo-500'>
        Hello world!
      </h1>
      <Card
        avatarUrl='https://randomuser.me/api/portraits/women/81.jpg'
        backgroundUrl='https://nomadlist.com/assets/img/places/gran-canaria-canary-islands-spain.jpg'
        city='Canary Island'
        country='Spain'
        detailUrl='http://localhost:3000/place/123'
        isFavorited={true}
        isUserOnline={true}
        rating={4.5}
      />
    </div>
  )
}

export default Home
