import Head from 'next/head'

const Home = () => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-3xl font-bold underline text-indigo-500'>
        Hello world!
      </h1>
    </div>
  )
}

export default Home
